app:
  working_dir: "/code"
  hostname: wiggum-ci
  environment:
    DJANGO_SETTINGS_MODULE: wiggum.settings.ci
  command: "/bin/bash -ci '/code/environment/ci/build.sh;/code/environment/ci/run.sh'"
  links:
    - postgres:db
  volumes:
    - ../:/code
