postgres:
  volumes:
    - ../data/postgres:/var/lib/postgresql/data
  ports:
    - "5432:5432"

app:
  ports:
    - "8009:8009"

  links:
    - postgres:db

  command: "/bin/true"

  environment:
    DJANGO_SETTINGS_MODULE: wiggum.settings.dev

  volumes:
    - ../:/code
    - ~/.gitconfig:/home/wiggum/.giticonfig:ro
    - ~/.ssh:/home/wiggum/.ssh:ro
